apiVersion: apps/v1
kind: Deployment
metadata:
  name: pipeline2-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pipeline2-app
  template:
    metadata:
      labels:
        app: pipeline2-app
    spec:
      containers:
        - name: nginx
          image: sshivaji555/pipeline2-app:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 80

