apiVersion: v1
kind: Service
metadata:
  name: pipeline2-service
spec:
  type: NodePort
  selector:
    app: pipeline2-app
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30081  # <-- change this to an unused port
